query Session {
  me {
    id
    username
    email
    avatarUrl
    bio
  }
}

mutation SignIn($input: LoginInput!) {
  login(loginInput: $input) {
    id
    username
    email
    avatarUrl
    bio
  }
}

mutation Register($input: CreateUserInput!) {
  createUser(createUserInput: $input) {
    id
    username
  }
}

mutation SignOut {
  logout
}

query PublicProfile($username: String!) {
  user(username: $username) {
    id
    username
    bio
    avatarUrl
    createdAt
  }
}

mutation SaveProfile($input: UpdateUserInput!) {
  updateUser(updateUserInput: $input) {
    id
    username
    email
    bio
    avatarUrl
  }
}
